package com.jingdong.common.address;

/* loaded from: classes5.dex */
public class AddressConstant {
    public static final String ADDRESS_LIST_BUSSINESS_LIFESERVICE_TYPE = "lifeServiceType";
    public static final String ADDRESS_LIST_BUSSINESS_MAOTAIFISSION_TYPE = "maoTaiFission";
    public static final String ADDRESS_LIST_BUSSINESS_MULTIPLE_ADDRESS = "multipleAddress";
    public static final String ADDRESS_LIST_BUSSINESS_MULTIPLE_ADDRESS_ID = "multipleAddressId";
    public static final String ADDRESS_LIST_BUSSINESS_MYCOUNT_TYPE = "myCountType";
    public static final String ADDRESS_LIST_BUSSINESS_ORDER_TYPE = "orderType";
    public static final String ADDRESS_LIST_BUSSINESS_PRODUCTDETAIL_TYPE = "productDetailType";
    public static final String ADDRESS_LIST_BUSSINESS_RN_TYPE = "rnType";
    public static final String ADDRESS_LIST_BUSSINESS_TYPE_KEY = "addressListBussinessTypeKey";
    public static final String ADDRESS_LIST_PLATFORM_TYPE_KEY = "addressListPlatformTypeKey";
    public static final String ADDRESS_LIST_PLUS_KEY = "isPlus";
    public static final String ADDRESS_LIST_SOURCE_MAP_KEY = "addressListSourceMapKey";
    public static final String ADDRESS_LIST_SOURCE_TAG_KEY = "sourceTag";
    public static final int BUSINESS_GIFT_TYPE = 2;
    public static final int BUSINESS_NORMAL_TYPE = 1;
    public static final int EASY_BUY_SOURCE_TYPE = 2;
    public static final int EDIT_PAGE_TYPE = 2;
    public static final String INTENT_EXTAS_ADDGLOBAL = "addressGlobal";
    public static final String INTENT_EXTAS_ADDRESS_TAG_LIST = "addressTagList";
    public static final String INTENT_EXTAS_BASE_ADDRESS_ID = "baseAddressId";
    public static final String INTENT_EXTAS_BASE_ID = "baseId";
    public static final String INTENT_EXTAS_BUSINESS_TYPE_KEY = "businessType";
    public static final String INTENT_EXTAS_CHECK_ADDRESS_KEY = "checkAddress";
    public static final String INTENT_EXTAS_CHECK_FLAG_KEY = "checkFlag";
    public static final String INTENT_EXTAS_DECRYPT_TYPE = "decryptType";
    public static final String INTENT_EXTAS_IS_ADDGLOBAL_REFRESH = "isAddressGlobalRefresh";
    public static final String INTENT_EXTAS_IS_FROM_ELDER = "isElder";
    public static final String INTENT_EXTAS_IS_FROM_PERFECT_DIALOG = "isFromPerfectDialog";
    public static final String INTENT_EXTAS_NEW_ADDRESS = "newaddrFromFillOrder";
    public static final String INTENT_EXTAS_PAGE_SOURCE_KEY = "pageSource";
    public static final String INTENT_EXTAS_PAGE_TYPE_KEY = "PageType";
    public static final String INTENT_EXTAS_SELECTED_ADDRESS_TAG = "selectedAddressTag";
    public static final String INTENT_EXTAS_SHOW_DELETE_BUTTON = "isShowDeleteButton";
    public static final String INTENT_EXTAS_SHOW_LOCATION = "show_location";
    public static final String INTENT_EXTAS_SUPPORT_ENCODE = "isSupportEncode";
    public static final String INTENT_EXTAS_SUPPORT_NEW_PARAM_ENCODE = "supportNewParamEncode";
    public static final String INTENT_EXTAS_SUPPORT_VOICE = "isSupportVoice";
    public static final String INTENT_EXTAS_USER_ADDRESS = "UserAddress";
    public static final String INTENT_EXTAS_USE_RECOMMEND_ADDRESS_INFO = "useRecommendAddressInfo";
    public static final String INTENT_EXTRAS_ADDRESS_INTELLIGENT_REMINDER = "addressIntelligentReminder";
    public static final String INTENT_EXTRAS_ADDRESS_LAYER_FLAG = "addressLayerFlag";
    public static final String INTENT_EXTRAS_ADDRESS_LIST_IS_EMPTY = "addressListIsEmpty";
    public static final String INTENT_EXTRAS_ADDRESS_LIST_LAYER_FLAG = "addressListLayerFlag";
    public static final String INTENT_EXTRAS_ADDRESS_LIST_POINT_DATA = "addressListLayerPointData";
    public static final String INTENT_EXTRAS_ADDRESS_POINT_DATA = "addressLayerPointData";
    public static final String INTENT_EXTRAS_DEFAULT_ADDRESS_MSG = "defaultAddressMsg";
    public static final String INTENT_EXTRAS_DEFAULT_ADDRESS_SWITCH = "defaultAddressSwitch";
    public static final String INTENT_EXTRAS_DEFAULT_ADDRESS_TITLE = "defaultAddressTitle";
    public static final String INTENT_EXTRAS_DEFAULT_HAS_SET_DEFAULT_ADDRESS = "hasSetDefaultAddress";
    public static final String INTENT_EXTRAS_IS_CLOSE_CLIPBOARD = "isCloseClipboard";
    public static final int NEW_PAGE_TYPE = 1;
    public static final int ORDER_SOURCE_TYPE = 1;
    public static final int PRODUCT_DETAIL_SOURCE_TYPE = 3;
}
